/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controladores.ControladorPaciente;
import javax.swing.ImageIcon;

/**
 *
 * @author Alvaro
 */
public class Paciente extends javax.swing.JFrame {

    private ControladorPaciente pc;
    
 /*  private ContMedico rp = new ContMedico(); 
   private HisMedico hm = new HisMedico();
   private CitasAgend ca = new CitasAgend();
    private void inicializarFormularios(){
        RP.setContentPane(rp);
        rp.setSize(500,500);
        RP.setSize(782,690);
        RP.setLocation(0,0);
        
        HM.setContentPane(hm);
        hm.setSize(500,500);
        HM.setSize(860,690);
        HM.setLocation(0,0);
        
        CA.setContentPane(ca);
        ca.setSize(500,500);
        CA.setSize(860,690);
        CA.setLocation(0,0);
     }*/
    public Paciente() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logo.png")).getImage());
        this.setLocation(200,200);
        this.setSize(800,700);
        setResizable(true);
        setTitle("Salud universal");
     //   this.inicializarFormularios();
        setLocationRelativeTo(null);
        
        pc = new ControladorPaciente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMcita = new javax.swing.JMenuItem();
        jMinfo = new javax.swing.JMenuItem();
        jMsair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blanco_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        Escritorio.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 660);

        getContentPane().add(Escritorio);
        Escritorio.setBounds(0, 0, 880, 670);

        jMenu1.setText("Menu");

        jMcita.setText("Agendar cita");
        jMenu1.add(jMcita);

        jMinfo.setText("Editar información");
        jMenu1.add(jMinfo);

        jMsair.setText("Cerrar sesion");
        jMenu1.add(jMsair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
                

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenuItem jMcita;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMinfo;
    public javax.swing.JMenuItem jMsair;
    // End of variables declaration//GEN-END:variables
}
